//本ponder为哦里冻编写，以CC BY-NC协议分发，使用请署名，禁止商用
Ponder.registry((e) => {
    e.create('fluxnetworks:flux_dust').scene('ori:flux_dust', '通量粉尘的获得', (scene)=>{
        scene.configureBasePlate(0, 0, 3)
        scene.showBasePlate()
        scene.idleSeconds(1)
        scene.world.setBlocks([1, 1, 1], 'minecraft:bedrock')
        scene.world.showSection([1, 1, 1], Direction.DOWN)
        scene.idle(15)
        scene.text(35, "现在我们有一个基岩……", [1.5, 1.5, 1.5])
        scene.idleSeconds(3)
        scene.world.setBlocks([1, 3, 1], 'minecraft:obsidian')
        scene.world.showSection([1, 3, 1], Direction.DOWN)
        scene.text(35, "让我们隔着一层空气放置一个黑曜石在此处", [1.5, 3.5, 1.5]).attachKeyFrame()
        scene.idleSeconds(3)
        scene.world.createItemEntity([1.5, 2.5, 1.5], Direction.DOWN, 'minecraft:redstone')
        scene.text(35, "在中间扔出一个（些）红石粉", [1.5, 2.5, 1.5]).attachKeyFrame()
        scene.idleSeconds(3)
        scene.showControls(15, [1.5, 3.5, 1.5], "LEFT").rightClick()
        scene.text(35, "……接下来右键这个黑曜石").attachKeyFrame()
        scene.idle(22)
        scene.world.setBlocks([1, 3, 1], "minecraft:air", false)
        scene.world.removeEntity(scene.world.createItemEntity([1.5, 2.5, 1.5], Direction.DOWN, 'minecraft:redstone'))
        scene.world.setBlocks([1, 2, 1], 'minecraft:obsidian')
        scene.world.showSection([1, 2, 1], Direction.DOWN)
        scene.world.createItemEntity([1.5, 3, 1.5], Direction.UP, 'fluxnetworks:flux_dust')
        scene.idle(22)
        scene.text(40, "就得到了一个（些）通量粉尘！", [1.5, 3.5, 1.5])
        scene.idle(50)
        scene.text(35, "当你获得了第一个通量方块之后，就可以让通量方块替代基岩的位置！", [1.5, 1.5, 1.5])
        scene.idle(55)
    })
})