//本ponder为哦里冻编写，以CC BY-NC协议分发，使用请署名，禁止商用
Ponder.registry((e) => {
    e.create('sfm:printing_press').scene('ori:printing_press', '如何使用压印机复制附魔书', (scene)=>{
        scene.configureBasePlate(0, 0, 5)
        scene.showBasePlate()
        scene.idleSeconds(1)
        scene.text(35, '现在是思索一下这个压印机的大好时机！')
        scene.idleSeconds(3)
        scene.text(35, '首先准备一个黑曜石和一个铁块').attachKeyFrame()
        scene.world.setBlocks([1, 1, 1], 'minecraft:obsidian')
        scene.world.setBlocks([1, 1, 3], 'minecraft:iron_block')
        scene.world.showSection([1, 1, 1], Direction.DOWN)
        scene.world.showSection([1, 1, 3], Direction.DOWN)
        scene.idleSeconds(3)
        let itemEntity1 = scene.world.createItemEntity([1.5, 2.5, 1.5], Direction.DOWN, 'minecraft:enchanted_book')
        scene.text(35, "在黑曜石上面扔任意数量的附魔书（数量越多品质越垃圾越好）", [1.5, 2, 1.5]).attachKeyFrame()
        scene.idleSeconds(3)
        scene.world.setBlocks([1, 3, 1], 'minecraft:anvil')
        scene.world.showSection([1, 3, 1], Direction.DOWN)
        scene.text(35, '然后释放铁砧！', [1.5, 3.5, 1.5]).attachKeyFrame()
        scene.idleSeconds(1)
        scene.world.setBlocks([1, 3, 1], "minecraft:air", false)
        scene.world.setBlocks([1, 2, 1], 'minecraft:anvil')
        scene.world.showSection([1, 2, 1], Direction.DOWN)
        scene.world.removeEntity(itemEntity1)
        scene.world.createItemEntity([1.5, 3, 1.5], Direction.UP, 'sfm:xp_shard')
        scene.idleSeconds(2)
        scene.world.setBlocks([3, 1, 1], 'tconstruct:crafting_station')
        scene.world.showSection([3, 1, 1], Direction.DOWN)
        scene.text(35, '接着我们需要一个工作台，并且用刚才铁砧砸出来的经验碎片合成出经验粘液').attachKeyFrame()
        scene.showControls(35, [3.5, 1.5, 1.5], "left").rightClick().withItem('sfm:xp_goop')
        scene.idleSeconds(3)
        scene.text(35, "在铁块上面扔你需要复制的那本附魔书（可以复制任何附魔书）", [1.5, 1.5, 3.5]).attachKeyFrame()
        let itemEntity2 = scene.world.createItemEntity([1.5, 2.5, 3.5], Direction.DOWN, 'minecraft:enchanted_book')
        scene.idleSeconds(3)
        scene.world.setBlocks([1, 3, 3], 'minecraft:anvil')
        scene.world.showSection([1, 3, 3], Direction.DOWN)
        scene.text(35, '同样的，释放铁砧！', [1.5, 3.5, 3.5]).attachKeyFrame()
        scene.idleSeconds(1)
        scene.world.setBlocks([1, 3, 3], "minecraft:air", false)
        scene.world.setBlocks([1, 1, 3], 'minecraft:anvil', false)
        scene.world.removeEntity(itemEntity2)
        scene.world.createItemEntity([1.5, 2.5, 3.5], Direction.DOWN, 'sfm:form')
        scene.idleSeconds(2)
        scene.rotateCameraY(135)
        scene.idleSeconds(1)
        scene.world.setBlocks([3, 1, 3], 'sfm:printing_press')
        scene.world.showSection([3, 1, 3], Direction.DOWN)
        scene.world.setBlocks([3, 3, 3], 'minecraft:piston')
        scene.world.showSection([3, 3, 3], Direction.DOWN)
        scene.world.modifyBlock([3, 3, 3], (state) => state.with("facing", "down"), false)
        scene.text(35, '准备一个压印机和一个活塞，活塞方向朝下').attachKeyFrame()
        scene.idleSeconds(3)
        scene.text(35, '在压印机的上面右键刚才得到的压印模板，经验粘液，和一本普通的书', [3.5, 1.5, 3.5])
        scene.showControls(10, [3.5, 1.5, 3.5], "left").rightClick().withItem('sfm:xp_goop')
        scene.idle(15)
        scene.showControls(10, [3.5, 1.5, 3.5], "left").rightClick().withItem('minecraft:book')
        scene.idle(15)
        scene.showControls(10, [3.5, 1.5, 3.5], "left").rightClick().withItem('sfm:form')
        //scene.world.modifyTileNBT([3, 1, 3], (nbt) => {nbt.form = {Items: [{Count: 1, Slot: 0, id: "sfm:form", tag: {reference: {Count: 1, id: "minecraft:enchanted_book", tag: {StoredEnchantments: [{id: "minecraft:fortune", lvl: 3}]}}}}], Size: 1}, nbt.ink = {Items: [{Count: 1, Slot: 0, id: "sfm:xp_goop"}], Size: 1}, nbt.paper = {Items: [{Count: 1, Slot: 0, id: "minecraft:book"}], Size: 1}}) 没搞懂
        scene.idle(20)
        scene.text(35, '给活塞一个红石信号！').attachKeyFrame()
        scene.world.setBlocks([3, 4, 3], 'minecraft:redstone_block')
        scene.world.showSection([3, 4, 3], Direction.DOWN)
        scene.world.modifyBlock([3, 3, 3], (state) => state.with("extended", "true"), false)
        scene.world.setBlocks([3, 2, 3], 'minecraft:piston_head')
        scene.world.showSection([3, 2, 3], Direction.DOWN)
        scene.world.modifyBlock([3, 2, 3], (state) => state.with("facing", "down"), false)
        scene.world.modifyBlock([3, 3, 3], (state) => state.with("short", "false"), false)
        scene.idleSeconds(3)
        scene.text(35, '关掉红石信号……').attachKeyFrame()
        scene.idle(25)
        scene.world.modifyBlock([3, 3, 3], (state) => state.with("extended", "false"), false)
        scene.world.setBlocks([3, 4, 3], 'minecraft:air', false)
        scene.world.setBlocks([3, 2, 3], 'minecraft:air', false)
        /*scene.world.modifyTileNBT([3, 1, 3], nbt => {
    nbt.paper = {
        Items: [
            {
                Count: 1,
                Slot: 0,
                id: "minecraft:enchanted_book"
            }
        ],
        Size: 1
    }
}, true)*/
        scene.idleSeconds(1)
        scene.text(60, '就能得到和那个附魔书一样的书了！（每次压印只会消耗一个经验粘液和一本书，模板不会被消耗）')
        scene.showControls(35, [3.5, 1.5, 3.5], "left").rightClick().withItem('minecraft:enchanted_book')
        scene.idleSeconds(5)
    })
})