ServerEvents.recipes(e=>{
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:white_dye"},"result":{"item":"gtceu:chemical_white_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:white_dye"},"result":{"item":"gtceu:chemical_white_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:light_gray_dye"},"result":{"item":"gtceu:chemical_light_gray_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:light_gray_dye"},"result":{"item":"gtceu:chemical_light_gray_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:gray_dye"},"result":{"item":"gtceu:chemical_gray_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:gray_dye"},"result":{"item":"gtceu:chemical_gray_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:black_dye"},"result":{"item":"gtceu:chemical_black_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:black_dye"},"result":{"item":"gtceu:chemical_black_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:brown_dye"},"result":{"item":"gtceu:chemical_brown_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:brown_dye"},"result":{"item":"gtceu:chemical_brown_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:red_dye"},"result":{"item":"gtceu:chemical_red_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:red_dye"},"result":{"item":"gtceu:chemical_red_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:orange_dye"},"result":{"item":"gtceu:chemical_orange_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:orange_dye"},"result":{"item":"gtceu:chemical_orange_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:yellow_dye"},"result":{"item":"gtceu:chemical_yellow_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:yellow_dye"},"result":{"item":"gtceu:chemical_yellow_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:lime_dye"},"result":{"item":"gtceu:chemical_lime_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:lime_dye"},"result":{"item":"gtceu:chemical_lime_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:green_dye"},"result":{"item":"gtceu:chemical_green_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:green_dye"},"result":{"item":"gtceu:chemical_green_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:cyan_dye"},"result":{"item":"gtceu:chemical_cyan_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:cyan_dye"},"result":{"item":"gtceu:chemical_cyan_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:light_blue_dye"},"result":{"item":"gtceu:chemical_light_blue_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:light_blue_dye"},"result":{"item":"gtceu:chemical_light_blue_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:blue_dye"},"result":{"item":"gtceu:chemical_blue_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:blue_dye"},"result":{"item":"gtceu:chemical_blue_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:purple_dye"},"result":{"item":"gtceu:chemical_purple_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:purple_dye"},"result":{"item":"gtceu:chemical_purple_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:magenta_dye"},"result":{"item":"gtceu:chemical_magenta_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:magenta_dye"},"result":{"item":"gtceu:chemical_magenta_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"tag":"tconstruct:casts/single_use/gem"},"cast_consumed":true,"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:pink_dye"},"result":{"item":"gtceu:chemical_pink_dye"}})
	e.custom({"type":"tconstruct:casting_table","cast":{"item":"tconstruct:gem_cast"},"cooling_time":15,"fluid":{"amount":72,"fluid":"gtceu:pink_dye"},"result":{"item":"gtceu:chemical_pink_dye"}})




})